'use client';

import { Award, ClipboardCheck, FileCheck2, ShieldCheck } from 'lucide-react';

import { formatDate } from '@/components/company-portal/company-ui';
import type { CompanyDashboardData } from '@/lib/company-types';

export function CompanyCertificates({ data }: { data: CompanyDashboardData }) {
  const readyCount = data.trainings.filter((item) => item.status === 'completed' && item.participant_count > 0).length;
  return <div className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><div className="border border-black/10 bg-white p-6"><Award className="size-6 text-[#8a6107]" /><strong className="mt-6 block text-3xl">{readyCount}</strong><span className="mt-2 block text-[9px] font-extrabold uppercase text-[#777]">Lotes prontos</span></div><div className="border border-black/10 bg-white p-6"><ClipboardCheck className="size-6 text-[#8a6107]" /><strong className="mt-6 block text-3xl">{data.participants.length}</strong><span className="mt-2 block text-[9px] font-extrabold uppercase text-[#777]">Certificados previstos</span></div><div className="border border-black/10 bg-white p-6"><ShieldCheck className="size-6 text-[#8a6107]" /><strong className="mt-6 block text-3xl">100%</strong><span className="mt-2 block text-[9px] font-extrabold uppercase text-[#777]">Vinculados à turma</span></div></div><div className="border-l-4 border-[#f2ad19] bg-white p-5"><strong className="text-sm uppercase">Etapa de geração</strong><p className="mt-2 text-sm leading-relaxed text-[#666]">O lote nasce dos participantes inscritos pelo QR. A geração automática do PDF e a assinatura digital serão liberadas em breve; o painel já mostra quais turmas estão prontas e quais aguardam conclusão.</p></div><div className="space-y-3">{data.trainings.map((training) => { const ready = training.status === 'completed' && training.participant_count > 0; return <article key={training.id} className="grid gap-5 border border-black/10 bg-white p-5 md:grid-cols-[auto_1fr_auto] md:items-center"><span className={`flex size-12 items-center justify-center ${ready ? 'bg-[#daf2df] text-[#17642d]' : 'bg-[#f2ad19]/18 text-[#8a6107]'}`}>{ready ? <FileCheck2 className="size-5" /> : <Award className="size-5" />}</span><div><span className="text-[9px] font-extrabold uppercase tracking-[0.11em] text-[#8a6107]">{training.client_name} · {training.nr}</span><h2 className="mt-1 text-sm font-bold uppercase">{training.title}</h2><p className="mt-1 text-[10px] text-[#888]">{training.participant_count} participante(s) · {formatDate(training.training_date)}</p></div><span className={`w-fit px-3 py-2 text-[9px] font-extrabold uppercase ${ready ? 'bg-[#daf2df] text-[#17642d]' : 'bg-[#f2ad19]/18 text-[#785303]'}`}>{ready ? 'Pronto para gerar' : 'Aguardando conclusão'}</span></article>; })}</div></div>;
}
